/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zjhlogo_spank_SpankLibrary */

#ifndef _Included_com_zjhlogo_spank_SpankLibrary
#define _Included_com_zjhlogo_spank_SpankLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    initialize
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjhlogo_spank_SpankLibrary_initialize
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_terminate
  (JNIEnv *, jclass);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_update
  (JNIEnv *, jclass);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_render
  (JNIEnv *, jclass);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    touchBegin
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_touchBegin
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    touchMove
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_touchMove
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    touchEnd
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_touchEnd
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    onKeyReturn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_onKeyReturn
  (JNIEnv *, jclass);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    onKeyHome
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_onKeyHome
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
