LIBSPANK_SOURCE_FILES := \
		$(LIBSPANK_SOURCE)/Config_Impl.cpp \
		$(LIBSPANK_SOURCE)/Core_Impl.cpp \
		$(LIBSPANK_SOURCE)/Image_Impl.cpp \
		$(LIBSPANK_SOURCE)/InputMgr.cpp \
		$(LIBSPANK_SOURCE)/Level2D_Impl.cpp \
		$(LIBSPANK_SOURCE)/Node_Impl.cpp \
		$(LIBSPANK_SOURCE)/Renderer2D_Impl.cpp \
		$(LIBSPANK_SOURCE)/Shader_Impl.cpp \
		$(LIBSPANK_SOURCE)/ShaderMgr_Impl.cpp \
		$(LIBSPANK_SOURCE)/Sprite_Impl.cpp \
		$(LIBSPANK_SOURCE)/Texture_Impl.cpp \
		$(LIBSPANK_SOURCE)/TextureMgr_Impl.cpp \
		$(LIBSPANK_SOURCE)/VertexAttribute_Impl.cpp \
		$(LIBSPANK_SOURCE)/math/IMath.cpp \
		$(LIBSPANK_SOURCE)/math/Matrix2x2.cpp \
		$(LIBSPANK_SOURCE)/math/Matrix3x3.cpp \
		$(LIBSPANK_SOURCE)/math/Matrix4x4.cpp \
		$(LIBSPANK_SOURCE)/math/Quaternion.cpp \
		$(LIBSPANK_SOURCE)/math/Vector2.cpp \
		$(LIBSPANK_SOURCE)/math/Vector3.cpp \
		$(LIBSPANK_SOURCE)/math/Vector4.cpp \
		$(LIBSPANK_SOURCE)/msg/IMsgBase.cpp \
		$(LIBSPANK_SOURCE)/msg/MsgMgr.cpp \
		$(LIBSPANK_SOURCE)/msg/MsgTouchEvent.cpp \
		$(LIBSPANK_SOURCE)/platforms/android/FileMgr_Impl.cpp \
		$(LIBSPANK_SOURCE)/platforms/android/Mutex_Impl.cpp \
		$(LIBSPANK_SOURCE)/platforms/android/RenderDevice_Impl.cpp \
		$(LIBSPANK_SOURCE)/platforms/android/util/DebugUtil_Impl.cpp \
		$(LIBSPANK_SOURCE)/platforms/android/unzip/unzip.cpp \
		$(LIBSPANK_SOURCE)/platforms/android/unzip/ioapi.cpp \
		$(LIBSPANK_SOURCE)/util/StreamReader.cpp \
		$(LIBSPANK_SOURCE)/util/StreamWriter.cpp \
