/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zjhlogo_spank_SpankLibrary */

#ifndef _Included_com_zjhlogo_spank_SpankLibrary
#define _Included_com_zjhlogo_spank_SpankLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    setPackagePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_setPackagePath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    initialize
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zjhlogo_spank_SpankLibrary_initialize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_terminate
  (JNIEnv *, jclass);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_step
  (JNIEnv *, jclass);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    touchBegin
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_touchBegin
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    touchMove
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_touchMove
  (JNIEnv *, jclass, jint, jfloat, jfloat);

/*
 * Class:     com_zjhlogo_spank_SpankLibrary
 * Method:    touchEnd
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_com_zjhlogo_spank_SpankLibrary_touchEnd
  (JNIEnv *, jclass, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
