/*!
 * \file MsgID.h
 * \date 18-05-2011 23:07:22
 * 
 * 
 * \author zjhlogo (zjhlogo@gmail.com)
 */
#ifndef __MSGID_H__
#define __MSGID_H__

enum MESSAGE_ID
{
	MI_UNKNOWN = 0,
	MI_DUMMY,

	MI_AAM_CREATE,
	MI_AAM_DESTROY,
	MI_AAM_START,
	MI_AAM_RESUME,
	MI_AAM_SAVE_INSTANCE_STATE,
	MI_AAM_PAUSE,
	MI_AAM_STOP,
	MI_AAM_CONFIGURATION_CHANGED,
	MI_AAM_LOW_MEMORY,
	MI_AAM_WINDOW_FOCUS_CHANGED,
	MI_AAM_NATIVE_WINDOW_CREATED,
	MI_AAM_NATIVE_WINDOW_DESTROYED,
	MI_AAM_INPUT_QUEUE_CREATED,
	MI_AAM_INPUT_QUEUE_DESTROYED,

};
#endif // __MSGID_H__